version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          name: Cypress Tests
          yarn: true
          start: yarn build
      - release:
          requires:
            - Cypress Tests
