version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          name: Cypress Tests
          yarn: true
          start: yarn develop
          wait-on: '--timeout 20000 http://localhost:8000'
      - release:
          requires:
            - Cypress Tests
